version: '3.8'

services:
  app:
    build: .
    ports:
      - "3000:3000"
      - "9229:9229"
    volumes:
      - .:/bc2024-6
    environment:
      - NODE_ENV=development
    command: npx nodemon -L --legacy-watch -- --inspect main.js -h localhost -p 3000 -c ./cache
